import type { TemplateMeta } from "@/lib/social-templates/types";

/**
 * Variant lists for the new type-only middle slides (Donation tiers,
 * Before/After, Multi-stat). The template registry has no entries for these
 * categories yet, so — like HERO_VARIANTS — we drive their picker from a
 * local list that renders through `presetForTemplate(id)`. v1 ships one
 * variant each; Phase 2 (the Claude Design build) expands every type to ten.
 */
function meta(id: string, name: string, description: string): TemplateMeta {
  return {
    id,
    name,
    description,
    platforms: ["instagram", "facebook"],
    category: id.split("-")[0]!,
    aspect: "square",
    size: { w: 1080, h: 1080 },
    slots: [],
    previewPath: "",
  } as TemplateMeta;
}

export const MIDDLE_VARIANTS: Record<string, TemplateMeta[]> = {
  tiers: [
    meta("tiers-a", "Impact ladder", "A heading over a £30 / £100 / £250 impact ladder — what each gift provides."),
    meta("tiers-b", "Over photo", "The impact ladder over a faint full-bleed photo with a scrim, ending with the URL."),
    meta("tiers-c", "Gold inverted", "A full gold field with forest ink — the ladder loud and high-contrast."),
    meta("tiers-d", "Single hero tier", "One colossal amount as the hero (‘£50 provides a week of food’) with the URL."),
    meta("tiers-e", "Split", "Photo left, the ladder on a forest panel right with a heading and the URL."),
    meta("tiers-f", "With total ask", "The ladder plus a closing total-ask line (‘£380 funds a family's month’)."),
    meta("tiers-g", "Zakat-framed", "A ‘Your Zakat’ framing — the same ladder, framed as zakat-eligible giving."),
    meta("tiers-h", "Two-tone", "A gold-bordered card — a forest panel carries the ladder, a cream band holds the URL."),
    meta("tiers-i", "Keyline card", "The ladder inside a gold keyline card on forest, with an eyebrow, heading and URL."),
    meta("tiers-j", "Scan to give", "A QR placeholder beside the ladder — the donor scans to give at any tier."),
  ],
  beforeafter: [
    meta("beforeafter-a", "Then & now", "Two figures split by a gold divider — a before/after contrast with a source line."),
    meta("beforeafter-b", "Vertical stack", "The before figure over the after figure, joined by a gold divider, with a source line."),
    meta("beforeafter-c", "Two photos", "A left/right photo split, each with a scrim and a before/after label and figure."),
    meta("beforeafter-d", "Connecting arrow", "The two figures on one row joined by a gold connecting arrow, with a source line."),
    meta("beforeafter-e", "Small then, big now", "A small ‘then’ figure vs a colossal ‘now’ figure, dramatising the collapse."),
    meta("beforeafter-f", "Two-tone", "A gold-bordered card — a forest panel carries the contrast, a cream band holds the source."),
    meta("beforeafter-g", "Over photo", "The before/after contrast over a faint full-bleed photo with a scrim and a source line."),
    meta("beforeafter-h", "Timeline", "A before → after on a horizontal timeline with a dateline at each end and a source."),
    meta("beforeafter-i", "Card-framed", "The before/after contrast inside a gold keyline card on forest, with a source line."),
    meta("beforeafter-j", "% change", "A giant ‘−80%’ change figure with a struck-through 36 → 7 context line and a source."),
  ],
  multistat: [
    meta("multistat-a", "By the numbers", "Three numbered figures stacked on forest — the scale of the crisis at a glance."),
    meta("multistat-b", "Single row", "The three figures across one row, with a heading and a source line."),
    meta("multistat-c", "Hero + supporting", "One hero stat up top, then two smaller supporting beats beneath, with a source."),
    meta("multistat-d", "Grid", "A 3-cell grid of bordered cells, each a figure and label, with a heading and source."),
    meta("multistat-e", "Over photo", "Three figures over a faint full-bleed photo with a scrim and a source line."),
    meta("multistat-f", "Two-tone", "A gold-bordered card — a forest panel carries the figures, a cream band holds the source."),
    meta("multistat-g", "Gold-ruled beats", "The three figures separated by thin gold rules, each with a small label."),
    meta("multistat-h", "Centred crest", "A ‘by the numbers’ crest — a gold keyline frame, a centred heading and three figures."),
    meta("multistat-i", "Connecting timeline", "The three figures on a connecting vertical timeline (gold spine + nodes)."),
    meta("multistat-j", "Ledger", "Left-aligned figures, right-aligned labels — a ‘ledger’ of the crisis, with a source."),
    meta("multistat-chart", "Bar chart", "A ranked horizontal bar chart — each figure a gold bar scaled to the largest, with a source line. Auto-fills from the report's numbers; edit any bar or value."),
  ],
  testimony: [
    meta("testimony-a", "Open-quote", "An oversized gold open-quote, the quote tight beneath in Barlow, a gold rule and an attribution row."),
    meta("testimony-b", "Portrait lower-third", "A full-bleed portrait with the quote in the lower third over a strong scrim, and the attribution."),
    meta("testimony-c", "Split", "Portrait left, a forest panel right carrying the open-quote, the quote and the attribution."),
    meta("testimony-d", "Portrait chip", "A small circular portrait on forest, the quote beneath and a gold rule + attribution row."),
    meta("testimony-e", "Crest", "A quiet centred crest — a small gold open-quote, the quote centred, a gold rule and the attribution."),
    meta("testimony-f", "Gold emphasis", "The quote in cream with one emphasis phrase set italic-gold on its own line, then the attribution."),
    meta("testimony-g", "Top portrait", "A portrait across the top, a forest panel below with the open-quote, the quote and the attribution."),
    meta("testimony-h", "Two-tone", "A gold-bordered card — a forest panel carries the quote, a cream band holds the attribution in dark ink."),
    meta("testimony-i", "Keyline card", "The quote framed in a gold keyline card on forest — open-quote, quote and attribution inside the frame."),
    meta("testimony-j", "Caption bar", "A full-bleed portrait with a solid forest caption bar at the foot carrying the quote and the attribution."),
  ],
  response: [
    meta("response-a", "Photo lower-third", "Full-bleed action photo with the response line, a gold rule and the eyebrow tag in the lower third."),
    meta("response-b", "Top photo + panel", "Action photo across the top with a forest panel below carrying the eyebrow, response line and a supporting line."),
    meta("response-c", "Split", "Action photo left, a forest panel right carrying the eyebrow, response line and support — a vertical 50/50."),
    meta("response-d", "Inset card", "Full-bleed action photo with a gold-bordered forest card floated low holding the eyebrow, response line and support."),
    meta("response-e", "Stat-backed", "The response line on forest with a small gold supporting stat beneath it as proof of impact."),
    meta("response-f", "Window crop", "An intimate action photo in a rounded window on forest, with the eyebrow and response line beneath."),
    meta("response-g", "Checklist", "A heading over a short 3-item checklist of what DR is providing — a gold diamond tick + item per row."),
    meta("response-h", "Two-tone", "A gold-bordered card — a forest panel carries the response line, a cream band holds the support and URL."),
    meta("response-i", "Caption bar", "Full-bleed action photo with a solid forest caption bar carrying the response line and a field credit."),
    meta("response-j", "How your gift helps", "A ‘How your gift helps’ framing — a heading, the response line, a gold-accented impact line and the URL."),
  ],
  fact: [
    meta("fact-a", "Photo lower-third", "Full-bleed photo with the sourced fact, a gold rule and a source tag in the lower third."),
    meta("fact-b", "Type-led", "Type-only on forest — an eyebrow, a big Anton fact, a gold rule and a gold source tag."),
    meta("fact-c", "Top photo + panel", "Photo across the top with a forest panel below carrying the fact and its source."),
    meta("fact-d", "Split", "Photo left, a forest panel right carrying the fact and source — a vertical 50/50."),
    meta("fact-e", "Keyline card", "The fact framed in a gold keyline card on forest, with eyebrow, fact and source."),
    meta("fact-f", "Lead-in detail", "A lead-in eyebrow, the fact, one pulled supporting detail line and a source."),
    meta("fact-g", "Caption bar", "Full-bleed photo with a solid forest caption bar carrying the fact and its source."),
    meta("fact-h", "Inset card", "Full-bleed photo with a gold-bordered forest card floated low holding the fact and source."),
    meta("fact-i", "Crest", "A quiet centred crest — diamond emblem, centred Anton fact, a gold rule and source meta."),
    meta("fact-j", "Two-tone", "A gold-bordered card — a forest panel carries the fact, a cream band holds the source."),
  ],
  stat: [
    meta("stat-a", "Colossal", "A colossal centred Anton numeral with an eyebrow above and a short label beneath."),
    meta("stat-b", "With context", "A big numeral in the upper area with a context sentence and a source line beneath."),
    meta("stat-c", "Bleeding numeral", "An oversized numeral bleeding off the edge as a graphic, the label set against it."),
    meta("stat-d", "Over photo", "Full-bleed photo with the stat and label in the lower third over a strong scrim."),
    meta("stat-e", "With unit", "A big numeral with a gold unit word beside it, a label and a source line."),
    meta("stat-f", "Gold inverted", "A full gold field with a colossal forest numeral and label — the loud stat."),
    meta("stat-g", "Split", "Photo left, a forest panel right carrying the stat, label and source."),
    meta("stat-h", "Crest", "A centred gold keyline frame around a big numeral, a gold rule and the label."),
    meta("stat-i", "Comparison", "A big numeral with a one-line ‘that's like…’ comparison giving it human scale."),
    meta("stat-j", "With beat", "The stat and label plus one small supporting footnote beat at the foot."),
  ],
  cta: [
    meta("cta-a", "Type-led", "Forest field, a big Anton ask, a gold rule and a DONATE NOW pill — the typographic close."),
    meta("cta-b", "Gold inverted", "A full gold field with forest ink and a forest DONATE pill — the loud, high-contrast close."),
    meta("cta-c", "Photo lower-third", "Full-bleed photo with the ask, a gold rule and a DONATE pill in the lower third."),
    meta("cta-d", "Crest", "Centred gold emblem, the ask, a gold rule and a centred DONATE pill inside a keyline frame."),
    meta("cta-e", "Split", "Photo left, a forest panel right carrying the ask and a DONATE pill."),
    meta("cta-f", "Stat-led", "A giant numeral + ‘need you now’, the ask and a centred DONATE pill."),
    meta("cta-g", "Quote-led", "A short testimony with attribution, then the ask and a DONATE pill."),
    meta("cta-h", "Urgency", "A gold ‘every hour counts’ chip, a big ask, a proximity tag and a DONATE pill."),
    meta("cta-i", "Scan to give", "A SCAN TO GIVE heading, a QR placeholder, the ask and a DONATE pill."),
    meta("cta-j", "Wordmark card", "A clean closing brand card — the DEEN RELIEF wordmark, a closing line and a DONATE pill."),
  ],
};
