"use client";

/**
 * Template picker modal. Lists templates grouped by category, with
 * name + description + a preview thumbnail (from
 * template.previewPath under /public — generated by the preview-builder
 * script). Clicking a template inserts a new slide.
 */

import { useEffect } from "react";
import type { TemplateMeta } from "@/lib/social-templates/types";
import type { TemplateGroups } from "./types";

interface Props {
  groups: TemplateGroups;
  onPick: (t: TemplateMeta) => void;
  onClose: () => void;
}

const CATEGORY_ORDER: string[] = [
  "hero",
  "fact",
  "stat",
  "response",
  "testimony",
  "tiers",
  "chapter",
  "cta",
];

const CATEGORY_LABELS: Record<string, string> = {
  hero: "Hero",
  fact: "Fact",
  stat: "Stat",
  response: "Response",
  testimony: "Testimony",
  tiers: "Tiers",
  chapter: "Chapter",
  cta: "Call to action",
};

export default function TemplatePicker({ groups, onPick, onClose }: Props) {
  // Esc closes
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  const orderedCategories = CATEGORY_ORDER.filter(
    (c) => (groups[c]?.length ?? 0) > 0
  );

  return (
    <div
      className="fixed inset-0 z-50 bg-charcoal/40 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl max-w-3xl w-full max-h-[85vh] overflow-hidden flex flex-col shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-5 py-3 border-b border-charcoal/8">
          <h2 className="font-heading font-bold text-lg text-charcoal">
            Add slide — pick a template
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="text-charcoal/40 hover:text-charcoal text-2xl leading-none"
            aria-label="Close template picker"
          >
            ×
          </button>
        </div>
        <div className="overflow-y-auto p-5 flex flex-col gap-6">
          {orderedCategories.length === 0 ? (
            <p className="text-center text-charcoal/55 py-8 text-sm">
              No templates available for this platform yet.
            </p>
          ) : (
            orderedCategories.map((category) => (
              <section key={category}>
                <h3 className="text-[11px] font-bold tracking-[0.18em] uppercase text-amber-dark mb-2">
                  {CATEGORY_LABELS[category] ?? category}
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {(groups[category] ?? []).map((meta) => (
                    <button
                      key={meta.id}
                      type="button"
                      onClick={() => onPick(meta)}
                      className="text-left bg-cream/40 hover:bg-cream border border-charcoal/10 hover:border-amber/40 rounded-xl p-3 transition-colors flex gap-3 items-start"
                    >
                      <div className="w-16 h-16 bg-charcoal/5 rounded shrink-0 overflow-hidden">
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                          src={meta.previewPath}
                          alt=""
                          className="w-full h-full object-cover"
                          onError={(e) => {
                            (e.currentTarget as HTMLImageElement).style.display =
                              "none";
                          }}
                        />
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="font-heading font-semibold text-[14px] text-charcoal leading-snug">
                          {meta.name}
                        </p>
                        <p className="text-[11.5px] text-charcoal/65 mt-1 leading-snug line-clamp-3">
                          {meta.description}
                        </p>
                      </div>
                    </button>
                  ))}
                </div>
              </section>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
