import type { TemplateMeta } from "@/lib/social-templates/types";

/**
 * The X (Twitter) single-image news-infographics (landscape 1200×675). Unlike
 * the Instagram carousel, X is ONE image per post — so each of these is a
 * dense infographic that carries the whole story: a disaster photo + the
 * headline + several report data points + a source + the wordmark. They differ
 * in LAYOUT, not in what they show. Ids match the `buildXSlide` routing (all
 * `x-*`) and the catalogue entries in template-lab/templateData.ts. `slots`/
 * `previewPath` are unused (these render through the layer/Satori pipeline).
 */
export const X_VARIANTS: TemplateMeta[] = [
  {
    id: "x-photo-facts",
    name: "Photo + fact ribbon",
    description: "Disaster photo full-bleed, headline over it, a 3-stat ribbon along the foot. The default.",
    platforms: ["x"],
    category: "hero",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-split-facts",
    name: "Photo + fact list",
    description: "Photo left, headline + a vertical list of figures on a forest panel right.",
    platforms: ["x"],
    category: "stat",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-top-photo-stats",
    name: "Photo top + stat row",
    description: "Photo banner across the top, headline + a 3-stat row beneath on forest.",
    platforms: ["x"],
    category: "stat",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-photo-card",
    name: "Photo + story card",
    description: "Photo full-bleed with a translucent forest card carrying headline + facts.",
    platforms: ["x"],
    category: "hero",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-hero-stat",
    name: "Photo + big stat",
    description: "Photo full-bleed, headline lower-left, one colossal figure + supporting facts right.",
    platforms: ["x"],
    category: "stat",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-ledger",
    name: "Numbered ledger",
    description: "Photo left, a numbered ledger (01/02/03/04) of figures on forest right.",
    platforms: ["x"],
    category: "stat",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-grid",
    name: "Photo + 2×2 grid",
    description: "Photo banner top, headline, then a 2×2 grid of four figures.",
    platforms: ["x"],
    category: "stat",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-overlay-list",
    name: "Darkened photo + list",
    description: "Photo darkened under a heavy overlay, headline + a bulleted fact list. The explainer.",
    platforms: ["x"],
    category: "fact",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-right-photo",
    name: "Facts + photo right",
    description: "Headline + fact list left on forest, photo right. Mirror of the split.",
    platforms: ["x"],
    category: "stat",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
  {
    id: "x-cta-facts",
    name: "Photo + facts + donate",
    description: "Photo left, headline + two figures + a DONATE ask on forest right.",
    platforms: ["x"],
    category: "cta",
    aspect: "wide",
    size: { w: 1200, h: 675 },
    slots: [],
    previewPath: "",
  },
];
