import type { Metadata, Viewport } from "next";
import AdminShell from "@/components/admin/AdminShell";
import OfflineIndicator from "@/components/admin/OfflineIndicator";
import PageTransition from "@/components/admin/PageTransition";
import PWAInstallPrompt from "@/components/admin/PWAInstallPrompt";
import ServiceWorkerRegistrar from "@/components/admin/ServiceWorkerRegistrar";
import { getAdminSession } from "@/lib/admin-session";

/**
 * Admin layout — wraps every /admin/* page with the shared chrome AND
 * the PWA install metadata (so trustees can install the admin to their
 * phone or desktop home screen as a standalone app).
 *
 * AdminShell internally bypasses its chrome on /admin/login (since
 * the login page has nothing to sign out of and no nav to traverse).
 *
 * PWA install behaviour:
 *   - Public site uses the root manifest at /manifest.webmanifest
 *     (generated by src/app/manifest.ts) — install icon = donor-facing
 *     branding, scope = whole site.
 *   - Admin overrides with /admin-manifest.webmanifest (static file in
 *     /public/) — start_url = /admin/donations, scope = /admin only,
 *     theme = admin chrome charcoal.
 *   - Because Next.js metadata composes child-overrides-parent, admin
 *     pages emit only the admin manifest link in <head>, not both.
 *   - Trustees can therefore install BOTH "Deen Relief" (donor app)
 *     and "DR Admin" (admin app) as separate home-screen icons if
 *     they want — they don't conflict.
 *
 * iOS install: Safari → Share → Add to Home Screen. Uses the
 * apple-touch-icon + apple-mobile-web-app-* meta tags. Note iOS
 * doesn't read the manifest file directly for install styling — it
 * uses the meta tags. We provide both so iOS and Android get the
 * right experience.
 *
 * Android install: Chrome → menu → Install app (or auto install
 * banner after engagement criteria are met). Reads the manifest.
 *
 * Production auth gate (NOT in the mockup):
 *   const { data } = await supabase.auth.getUser();
 *   if (!data.user) redirect("/admin/login");
 *   const { data: adminRow } = await supabase
 *     .from("admin_users")
 *     .select("id")
 *     .eq("user_id", data.user.id)
 *     .maybeSingle();
 *   if (!adminRow) redirect("/admin/login?error=not-authorised");
 *
 * The layout returns server-side, so the gate runs before any page
 * data fetches. Saves leaking sensitive donor data via SSR.
 */
export const metadata: Metadata = {
  // Each admin page sets its own full title (with " | ... Admin" suffix
  // included). Setting only `default` here means pages without their own
  // metadata fall back to "Deen Relief Admin", with no template wrapping
  // that would double-suffix titles that already carry the brand.
  title: { default: "Deen Relief Admin", template: "%s" },
  manifest: "/admin-manifest.webmanifest",
  applicationName: "Deen Relief Admin",
  // iOS-specific install metadata. Apple's WebKit uses these instead of
  // the manifest for "Add to Home Screen" behaviour.
  appleWebApp: {
    capable: true,
    title: "DR Admin",
    statusBarStyle: "default",
  },
  icons: {
    // Override the public-site apple icon for /admin so trustees see
    // the same icon whether they install via Safari or Chrome on iOS.
    apple: "/icon-192.png",
  },
  // Make sure the admin section never shows up in search results, even
  // if the auth gate is somehow bypassed.
  robots: { index: false, follow: false },
};

export const viewport: Viewport = {
  themeColor: "#1A1A2E",
  width: "device-width",
  initialScale: 1,
  // viewportFit:'cover' tells WebKit/Chromium to extend the page
  // under the notch + home-indicator areas on modern iPhones,
  // and to expose `env(safe-area-inset-*)` to our CSS so the
  // admin shell can apply correct padding rather than getting
  // clipped behind the system UI in PWA standalone mode.
  viewportFit: "cover",
};

export default async function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Read the session so AdminShell can display the actual signed-in
  // email next to "Sign out" rather than a hardcoded placeholder.
  // getAdminSession returns null on /admin/login (no cookie yet) —
  // AdminShell falls back to its default in that case, but the login
  // page bypasses the chrome anyway so the fallback never renders.
  const session = await getAdminSession();
  return (
    <>
      {/* Set body[data-route="admin"] on the client so the
          admin-only touch-target / safe-area CSS in globals.css
          can scope to admin routes without affecting the public
          site. Effect runs once on mount, cleared on unmount —
          a SPA-style admin → public transition flips the flag
          off. */}
      <AdminRouteAttribute />
      {/* Service worker registers in the background so the admin
          shell + offline page get cached for fast subsequent loads
          and offline fallback. */}
      <ServiceWorkerRegistrar />
      {/* Top-of-page banner that surfaces when the browser detects
          we've lost connectivity — gives the trustee context for
          why their save actions might be failing. */}
      <OfflineIndicator />
      <AdminShell signedInAs={session?.email}>
        {/* Wrap children in PageTransition so a subtle fade-up
            fires on every admin route change. Keyed off pathname
            internally — pure CSS animation, ~250ms, respects
            prefers-reduced-motion. */}
        <PageTransition>{children}</PageTransition>
      </AdminShell>
      {/* Custom install prompt — Android: intercepts the
          beforeinstallprompt event for a properly branded install
          banner. iOS Safari: 2-line hint pointing at the Share
          button. Both auto-dismiss for 7 days after the user opts
          out so we don't nag. */}
      <PWAInstallPrompt />
    </>
  );
}

// Tiny client component just for the body attribute. Kept inline
// so the admin layout itself stays a server component for the
// auth-gate pattern when it gets wired.
function AdminRouteAttribute() {
  return (
    <script
      dangerouslySetInnerHTML={{
        __html: `document.body.dataset.route='admin';`,
      }}
    />
  );
}
