import type { EditorSlide } from "@/lib/social-editor/types";

/**
 * A seeded hero slide for the editor lab — a couple of text layers, a
 * photo zone, the forest panel, and an amber rule. Geometry is in the
 * 1080-board space the real templates use, so it exercises the canvas
 * the same way a migrated template will.
 */
export const DEMO_SLIDE: EditorSlide = {
  id: "demo-1",
  width: 1080,
  height: 1080,
  background: "#163827",
  layers: [
    {
      id: "ly_photo",
      type: "image",
      x: 0,
      y: 0,
      w: 1080,
      h: 670,
      rotation: 0,
      opacity: 1,
      locked: false,
      src: "",
      objectFit: "cover",
      radius: 0,
    },
    {
      id: "ly_panel",
      type: "shape",
      x: 0,
      y: 670,
      w: 1080,
      h: 410,
      rotation: 0,
      opacity: 1,
      locked: false,
      shape: "rect",
      fill: "#163827",
      stroke: "#163827",
      strokeWidth: 0,
      radius: 0,
    },
    {
      id: "ly_rule",
      type: "shape",
      x: 56,
      y: 724,
      w: 96,
      h: 6,
      rotation: 0,
      opacity: 1,
      locked: false,
      shape: "line",
      fill: "transparent",
      stroke: "#D4A843",
      strokeWidth: 6,
      radius: 0,
    },
    {
      id: "ly_eyebrow",
      type: "text",
      x: 56,
      y: 746,
      w: 600,
      h: 36,
      rotation: 0,
      opacity: 0.85,
      locked: false,
      text: "FROM GAZA · 25 MAY 2026",
      fontFamily: '"DM Sans", sans-serif',
      fontSize: 22,
      fontWeight: 600,
      italic: false,
      underline: false,
      uppercase: true,
      color: "#D4A843",
      align: "left",
      lineHeight: 1.2,
      letterSpacing: 3,
    },
    {
      id: "ly_title",
      type: "text",
      x: 56,
      y: 792,
      w: 968,
      h: 170,
      rotation: 0,
      opacity: 1,
      locked: false,
      text: "881 KILLED SINCE THE CEASEFIRE.",
      fontFamily: '"DM Sans", sans-serif',
      fontSize: 76,
      fontWeight: 800,
      italic: false,
      underline: false,
      uppercase: true,
      color: "#F7F3E8",
      align: "left",
      lineHeight: 1.0,
      letterSpacing: 0,
    },
    {
      id: "ly_body",
      type: "text",
      x: 56,
      y: 966,
      w: 920,
      h: 80,
      rotation: 0,
      opacity: 0.82,
      locked: false,
      text: "1.7 million people remain across 1,600 displacement sites — 88% of them makeshift.",
      fontFamily: '"DM Sans", sans-serif',
      fontSize: 24,
      fontWeight: 400,
      italic: false,
      underline: false,
      uppercase: false,
      color: "#F7F3E8",
      align: "left",
      lineHeight: 1.4,
      letterSpacing: 0,
    },
  ],
};
