-- Migration 023: store the auto-drafted launch packet on each emergency event.
--
-- Phase 4 (Task #13) of the Social Operations Platform. When the SMM clicks
-- "Draft launch packet" on a detected emergency, src/lib/first-response-packet.ts
-- calls Claude (Opus 4.7) with the event payload, matched coverage rows, and
-- the Deen Relief brand-voice spec; the structured response lands here.
--
-- One column does the job: a single jsonb blob. Schema lives in code
-- (src/lib/first-response-packet.ts), enforced via Zod / Claude's structured
-- output. Storing as jsonb (not text) lets us index or query individual
-- fields later without a schema change.
--
-- We also record who generated it and when, so the SMM/admin can see staleness
-- ("drafted 2 hours ago, before the magnitude was revised") and trace audit.
--
-- Idempotent.

alter table emergency_events
  add column if not exists draft_packet_json jsonb,
  add column if not exists draft_packet_generated_at timestamptz,
  add column if not exists draft_packet_generated_by_email text,
  -- Token usage from the API call — useful for cost reporting + tuning.
  add column if not exists draft_packet_model text,
  add column if not exists draft_packet_input_tokens int,
  add column if not exists draft_packet_output_tokens int;

comment on column emergency_events.draft_packet_json is
  'Auto-drafted launch packet (headline, body, social posts, email, press release, etc) generated by Claude. Schema enforced by src/lib/first-response-packet.ts. SMM reviews, edits, approves; one-click launch (Phase 4b) reads from here.';
